.PHONY: clean All

All:
	@echo "----------Building project:[ TryingToMakeAGame - Debug ]----------"
	@cd "/home/naufal/Dokumen/Projects/TryingToMakeAGame" && "$(MAKE)" -f  "TryingToMakeAGame.mk"
clean:
	@echo "----------Cleaning project:[ TryingToMakeAGame - Debug ]----------"
	@cd "/home/naufal/Dokumen/Projects/TryingToMakeAGame" && "$(MAKE)" -f  "TryingToMakeAGame.mk" clean
